
// AUTOGENERATED, DO NOT EDIT
// Type definitions for server implementations of ports.
// package: codegen.test
// file: test/api_test.proto
using Cysharp.Threading.Tasks;
using rpc_csharp;
using Google.Protobuf.WellKnownTypes;

namespace Codegen.Test {
public interface IClientBookService
{
  UniTask<Book> GetBook(GetBookRequest request);

  IUniTaskAsyncEnumerable<Book> QueryBooks(QueryBooksRequest request);

  UniTask<Book> GetBookStream(IUniTaskAsyncEnumerable<GetBookRequest> streamRequest);

  IUniTaskAsyncEnumerable<Book> QueryBooksStream(IUniTaskAsyncEnumerable<GetBookRequest> streamRequest);

  UniTask<Empty> Empty(Empty request);
}

public class ClientBookService : public IClientBookService
{
  private readonly RpcClientModule module;

  public ClientBookService(RpcClientModule module)
  {
      this.module = module;
  }

  
  public UniTask<Book> GetBook(GetBookRequest request)
  {
      return module.CallUnaryProcedure<Book>("GetBook", request);
  }

  public IUniTaskAsyncEnumerable<Book> QueryBooks(QueryBooksRequest request)
  {
      return module.CallServerStream<Book>("QueryBooks", request);
  }

  public UniTask<Book> GetBookStream(IUniTaskAsyncEnumerable<GetBookRequest> streamRequest)
  {
      return module.CallClientStream<Book>("GetBookStream", streamRequest);
  }

  public IUniTaskAsyncEnumerable<Book> QueryBooksStream(IUniTaskAsyncEnumerable<GetBookRequest> streamRequest)
  {
      return module.CallBidirectionalStream<Book>("QueryBooksStream", streamRequest);
  }

  public UniTask<Empty> Empty(Empty request)
  {
      return module.CallUnaryProcedure<Empty>("Empty", request);
  }

}
}
