
// AUTOGENERATED, DO NOT EDIT
// Type definitions for server implementations of ports.
// package: codegen.test
// file: test/api_test.proto
using Cysharp.Threading.Tasks;
using rpc_csharp;
using Google.Protobuf.WellKnownTypes;

namespace codegen.test {
public class ClientBookService
{
  private readonly RpcClientModule module;

  public ClientBookService(RpcClientModule module)
  {
      this.module = module;
  }

  public UniTask<test_api_test_pb.Book> GetBook(GetBookRequest request)
  {
      return module.CallUnaryProcedure<test_api_test_pb.Book>("GetBook", request);
  }

  public IUniTaskAsyncEnumerable<test_api_test_pb.Book> QueryBooks(QueryBooksRequest request)
  {
      return module.CallServerStream<test_api_test_pb.Book>("QueryBooks", request);
  }

  public UniTask<test_api_test_pb.Book> GetBookStream(IUniTaskAsyncEnumerable<GetBookRequest> streamRequest)
  {
      return module.CallClientStream<test_api_test_pb.Book>("GetBookStream", streamRequest);
  }

  public IUniTaskAsyncEnumerable<test_api_test_pb.Book> QueryBooksStream(IUniTaskAsyncEnumerable<GetBookRequest> streamRequest)
  {
      return module.CallBidirectionalStream<test_api_test_pb.Book>("QueryBooksStream", streamRequest);
  }

  public UniTask<google_protobuf_empty_pb.Empty> Empty(Empty request)
  {
      return module.CallUnaryProcedure<google_protobuf_empty_pb.Empty>("Empty", request);
  }
}
}
